### PR TITLE
Added Pincode in the Message which is displayed

### PR DESCRIPTION
**Pull request by joseph9991**
Showing the Pincode in the message can help in catalyzing the Booking Process as searching by Pincode in cowin is much easier than going by District

### CODE REVIEW

**Comment by abhinavdc** [comment]
Thanks for the PR @joseph9991

**Comment by joseph9991** [comment]
Kudos to your work!! Keep it up!
 Do let me know if I can help you out with anything else! I was looking at the Issues and couldn't understand what is needed to be done for #20 (Sputnik Vaccine to be added in List).

**Comment by abhinavdc** [comment]
That'll be great if you can pick that up too, but no pressure. Right now the accepted params for `--vaccine` flag is `covaxin` or `covishield`. The results will be filtered based on vaccine param we pass in and the value of `session.vaccine` in the API response. Since we now have Sputnik also available in India we need to allow the `--vaccine` flag to accept the new vaccine as well not just `covaxin` and `covishield`. So the work will be to find out a place in cowin which has Sputnik and check the API to see what the value is for `session.vaccine`. It could be `sputnik` or `sputnikv` or something similar. Then allow this to be passed in to the app as --vaccine flag by updating the validation. So in the code we would only need to change the args validation and udpate the readme file.

I hope this was clear but if you still have doubts let me know. I can break it down to you further.

**Comment by joseph9991** [comment]
Yup crystal clear. 
Some script can be cooked up to run on all the locations of Telangana or some other state where Sputnik is available and we can find out all the vaccines that are available. Hence, this will give us the exact name of Sputnik as well!

Let's see, I will try to do something this week. Meanwhile, someone might find it faster than me! If that happens well and good otherwise I will definitely sit and work this out.

**Pull request merged**
